services:
  postgres:
    container_name: proxia-postgres
    image: postgres:17
    environment:
      POSTGRES_DB: proxia
      POSTGRES_USER: proxia
      POSTGRES_PASSWORD: proxia
    ports:
      - '5432:5432'
    volumes:
      - ./.compose/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U proxia -d proxia']
      interval: 5s
      timeout: 5s
      retries: 5
